# Common File to be use in All env
application:
  name: "iewc-salesdoc-eapi"
milestone:
  category: "LOG"
  
 #logging info

source: "iewc-user"
target: "salesdoc-papi"
requestMessage: "Received salesdoc request from iewc user"
responseMessage: "Response sent back to iewc user"
